### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by gukoff** [maartenbreddels/per4m#8]
Hi @maartenbreddels , could you please add an explicit LICENSE to this project?

When there's no license, the default copyright laws apply, and "[no one may reproduce, distribute, or create derivative works from your work](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license)". I wonder if this is intended.

**Comment by maartenbreddels** [comment]
Hi,

The license is MIT, which is visible from https://github.com/maartenbreddels/per4m/blob/master/setup.py#L18
It's not as visible as a separate LICENSE file. If you prefer that, feel free to open a PR.

Regards,

Maarten
